// GERADO AUTOMATICAMENTE por scripts/generate_sleep_cards.py
// Fonte: assets/data/sleep_awareness_cards.xlsx — não editar à mão.
// Para atualizar: troque a planilha e rode o script de novo.

export interface SleepAwarenessCard {
  text: string;
  tags: string;
  author: string;
  source: string;
}

export const SLEEP_AWARENESS_CARDS: SleepAwarenessCard[] = [
  {
    text: "\"O sono é seu sistema de suporte à vida e a melhor tentativa que a Mãe Natureza já fez em direção à imortalidade.\"\n— Dr. Matthew Walker (neurocientista, UC Berkeley, autor de \"Why We Sleep\")",
    tags: "Importância geral / Evolução, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Os seres humanos são a única espécie que se priva deliberadamente de sono sem nenhuma razão aparente.\"\n— Dr. Matthew Walker (TED, 2019)",
    tags: "Importância evolutiva, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Homens que dormem cinco horas por noite têm testículos significativamente menores do que os que dormem sete horas ou mais.\"\n— Dr. Matthew Walker (TED, 2019)",
    tags: "Testosterona / Massa magra, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Homens que dormem apenas quatro a cinco horas por noite têm um nível de testosterona equivalente ao de alguém 10 anos mais velho. A falta de sono envelhece um homem em uma década nesse aspecto crítico de bem-estar.\"\n— Dr. Matthew Walker (TED, 2019)",
    tags: "Testosterona / Massa magra, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Se você está fazendo dieta mas não dorme o suficiente, 70% do peso que perder virá de massa magra — músculo — e não de gordura. Seu corpo se torna avarento em ceder gordura quando está privado de sono.\"\n— Dr. Matthew Walker (Joe Rogan #1109; Peter Attia Drive #49)",
    tags: "Massa magra / Composição corporal, sono",
    author: "Dr. Matthew Walker",
    source: "https://peterattiamd.com/matthewwalker3/",
  },
  {
    text: "\"Após apenas uma semana dormindo somente quatro a cinco horas por noite, os níveis de glicose ficam tão desregulados que você seria classificado como pré-diabético.\"\n— Dr. Matthew Walker (\"Why We Sleep\", Cap. 8)",
    tags: "Sensibilidade à insulina, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/lack-of-sleep-glucose-insensitivity-pre-diabetes",
  },
  {
    text: "\"Após apenas uma noite de quatro ou cinco horas de sono, suas células natural killer — as que atacam as células cancerígenas que aparecem no seu corpo todos os dias — caem 70%.\"\n— Dr. Matthew Walker (TED, 2019)",
    tags: "Sistema imune / Câncer, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Na primavera, quando perdemos uma hora de sono (horário de verão), há um aumento de 24% nos infartos no dia seguinte. No outono, quando ganhamos uma hora, há uma redução de 21% nos infartos.\"\n— Dr. Matthew Walker (TED, 2019)",
    tags: "Biomarcadores / Cardiovascular, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Se você não dorme na primeira noite após aprender algo, perde a chance de consolidar aquelas memórias — mesmo que durma muito depois. Em termos de memória, o sono não é como um banco. Você não pode acumular dívida e pagar depois.\"\n— Dr. Matthew Walker (TED, 2019)",
    tags: "Performance cognitiva / Memória, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Durante o sono profundo, existe uma espécie de sistema de esgoto dentro do cérebro — o sistema glinfático — que entra em alta velocidade e remove toxinas metabólicas acumuladas durante a vigília, incluindo uma proteína tóxica e pegajosa chamada beta-amiloide, associada ao Alzheimer.\"\n— Dr. Matthew Walker (TED-Ed, \"Sleeping with Science\")",
    tags: "Alzheimer / Sistema glinfático, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_what_s_the_connection_between_sleep_and_alzheimer_s_disease/transcript",
  },
  {
    text: "\"Quanto menor seu sono, menor sua vida.\"\n— Dr. Matthew Walker (The Guardian, 2017)",
    tags: "Longevidade / Mortalidade, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.theguardian.com/lifeandstyle/2017/sep/24/why-lack-of-sleep-health-worst-enemy-matthew-walker-why-we-sleep",
  },
  {
    text: "\"Nenhum aspecto da nossa biologia sai ileso da privação de sono. Ela penetra em cada canto e fresta possível. E ainda assim ninguém está fazendo nada a respeito.\"\n— Dr. Matthew Walker (The Guardian, 2017)",
    tags: "Importância geral / Biomarcadores, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.theguardian.com/lifeandstyle/2017/sep/24/why-lack-of-sleep-health-worst-enemy-matthew-walker-why-we-sleep",
  },
  {
    text: "\"O sono é a coisa mais eficaz que podemos fazer para reiniciar a saúde do nosso cérebro e do nosso corpo a cada dia — a melhor tentativa da Mãe Natureza contra a morte.\"\n— Dr. Matthew Walker (\"Why We Sleep\", 2017)",
    tags: "Importância geral, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.goodreads.com/quotes/9059444-sleep-is-the-single-most-effective-thing-we-can-do",
  },
  {
    text: "\"O sono é o canivete suíço da saúde. Quando o sono é deficiente, há doença e adoecimento. Quando o sono é abundante, há vitalidade e saúde.\"\n— Dr. Matthew Walker (NPR Hidden Brain, 2017)",
    tags: "Importância geral / Biomarcadores, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.npr.org/2017/11/13/563831137/the-swiss-army-knife-of-health-a-good-nights-sleep",
  },
  {
    text: "\"Sem sono, há baixa energia e doença. Com sono, há vitalidade e saúde.\"\n— Dr. Matthew Walker (Berkeley News, 2019)",
    tags: "Importância geral, sono",
    author: "Dr. Matthew Walker",
    source: "https://news.berkeley.edu/2019/05/13/walker-tedtalk/",
  },
  {
    text: "\"Em 1942, mais de 90% dos americanos dormiam mais de seis horas por noite. Hoje, quase 50% sobrevivem com seis horas ou menos. Precisamos reivindicar nosso direito a uma noite completa de sono, sem constrangimento ou o estigma de preguiça.\"\n— Dr. Matthew Walker (Berkeley News, 2019)",
    tags: "Cultura / Hábito, sono",
    author: "Dr. Matthew Walker",
    source: "https://news.berkeley.edu/2019/05/13/walker-tedtalk/",
  },
  {
    text: "\"A dizimação do sono nas nações industrializadas está tendo um impacto catastrófico em nossa saúde, bem-estar, e até na segurança e educação de nossas crianças. É uma epidemia silenciosa de privação de sono — um dos maiores desafios de saúde pública do século 21.\"\n— Dr. Matthew Walker (TED, 2019)",
    tags: "Saúde pública, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.ted.com/talks/matt_walker_sleep_is_your_superpower/transcript",
  },
  {
    text: "\"Tire o sono profundo de um humano por uma única noite e você verá um aumento significativo nos níveis circulantes de beta-amiloide e tau no dia seguinte.\"\n— Dr. Matthew Walker (citado por Peter Attia; estudo Shokri-Kojori et al., PNAS 2018)",
    tags: "Alzheimer / Sistema glinfático, sono",
    author: "Dr. Matthew Walker",
    source: "https://peterattiamd.com/the-connection-between-sleep-and-alzheimers-disease/",
  },
  {
    text: "\"O sono é a fundação sobre a qual aquelas duas outras coisas [dieta e exercício] se apoiam. Não é o terceiro pilar da boa saúde — penso que é a fundação.\"\n— Dr. Matthew Walker (Peter Attia Drive #47)",
    tags: "Importância geral, sono",
    author: "Dr. Matthew Walker",
    source: "https://peterattiamd.com/matthewwalker1/",
  },
  {
    text: "\"Nós não conseguimos descobrir uma única condição psiquiátrica em que o sono seja normal.\"\n— Dr. Matthew Walker (Huberman Lab Guest Series, Ep. 5)",
    tags: "Saúde mental, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.hubermanlab.com/episode/guest-series-dr-matt-walker-improve-sleep-to-boost-mood-emotional-regulation",
  },
  {
    text: "\"Melhor nootrópico: sono. Melhor alívio de estresse: sono. Melhor liberação de trauma: sono. Melhor reforço imunológico: sono. Melhor aumento hormonal: sono. Melhor estabilizador emocional: sono.\"\n— Dr. Andrew Huberman (neurocientista, Stanford / Huberman Lab Podcast)",
    tags: "Importância geral, sono",
    author: "Dr. Andrew Huberman",
    source: "https://x.com/hubermanlab/status/1438316907598258177",
  },
  {
    text: "\"O sono é a fundação da nossa saúde mental, saúde física e desempenho.\"\n— Dr. Andrew Huberman (Huberman Lab, \"Toolkit for Sleep\")",
    tags: "Importância geral / Saúde mental, sono",
    author: "Dr. Andrew Huberman",
    source: "https://www.hubermanlab.com/newsletter/toolkit-for-sleep",
  },
  {
    text: "\"Pilares da saúde mental, física e do desempenho: 1) Sono  2) Luz solar  3) Movimento  4) Nutrientes  5) Relacionamentos.\"\n— Dr. Andrew Huberman (Huberman Lab Podcast)",
    tags: "Importância geral, sono",
    author: "Dr. Andrew Huberman",
    source: "https://x.com/hubermanlab/status/1617218306934722564",
  },
  {
    text: "\"Ver luz solar pela manhã aumenta os níveis matinais de cortisol em 50% — algo bom logo cedo, porque eleva a função imune, o estado de alerta e 'arma' um cronômetro para você adormecer ~14-16 horas depois.\"\n— Dr. Andrew Huberman (Huberman Lab Podcast)",
    tags: "Ritmo circadiano / Higiene do sono, sono",
    author: "Dr. Andrew Huberman",
    source: "https://x.com/hubermanlab/status/1603409213589401601",
  },
  {
    text: "\"Para garantir uma péssima noite de sono: 1) Cochilar mais de 90 min à tarde. 2) Mais de 100 mg de cafeína após as 16h. 3) Comer logo antes de dormir. 4) Dormir nos fins de semana mais de 1 hora além do habitual.\"\n— Dr. Andrew Huberman (Huberman Lab Podcast)",
    tags: "Higiene do sono, sono",
    author: "Dr. Andrew Huberman",
    source: "https://www.linkedin.com/posts/andrew-huberman_to-ensure-a-terrible-nights-sleep-1-activity-6955560964519866368-dPPC",
  },
  {
    text: "\"O comportamento simples que acredito que todo mundo deveria adotar é ver luz, idealmente luz solar, por 2 a 10 minutos toda manhã ao acordar.\"\n— Dr. Andrew Huberman (Huberman Lab Ep. 2)",
    tags: "Ritmo circadiano, sono",
    author: "Dr. Andrew Huberman",
    source: "https://www.hubermanlab.com/episode/master-your-sleep-and-be-more-alert-when-awake",
  },
  {
    text: "\"A adenosina é uma molécula no nosso sistema nervoso e no corpo que se acumula quanto mais tempo ficamos acordados. Ela cria uma espécie de impulso de sono — uma fome de sono.\"\n— Dr. Andrew Huberman (Huberman Lab Ep. 2)",
    tags: "Pressão do sono / Cafeína, sono",
    author: "Dr. Andrew Huberman",
    source: "https://www.hubermanlab.com/episode/master-your-sleep-and-be-more-alert-when-awake",
  },
  {
    text: "\"A ansiedade matinal pode literalmente ser toda resolvida ao corrigir seu ritmo de cortisol. Picos tardios de cortisol estão correlacionados com depressão, ansiedade e várias outras coisas.\"\n— Dr. Andrew Huberman (Huberman Lab Podcast)",
    tags: "Saúde mental, sono",
    author: "Dr. Andrew Huberman",
    source: "https://www.hubermanlab.com/episode/using-cortisol-and-adrenaline-to-boost-our-energy-and-immune-system",
  },
  {
    text: "\"Uma única noite de sono ruim pode cortar sua sensibilidade à insulina em até 25%. Significa que até uma noite mal dormida pode impactar significativamente a capacidade do seu corpo de regular a glicemia.\"\n— Dra. Rhonda Patrick (FoundMyFitness; estudo Donga et al., JCEM 2010)",
    tags: "Sensibilidade à insulina, sono",
    author: "Dra. Rhonda Patrick",
    source: "https://x.com/foundmyfitness/status/1902094103413977590",
  },
  {
    text: "\"Mesmo uma única noite de sono perdido pode levar à resistência à insulina de curto prazo em pessoas saudáveis — mas o treino intervalado de alta intensidade ajuda a neutralizar esse efeito.\"\n— Dra. Rhonda Patrick (FoundMyFitness)",
    tags: "Sensibilidade à insulina / Exercício, sono",
    author: "Dra. Rhonda Patrick",
    source: "https://x.com/foundmyfitness/status/1719779566573719707",
  },
  {
    text: "\"A regularidade do seu sono pode ser quase tão importante quanto o total de horas. Pessoas com padrões de sono altamente irregulares têm risco 26% maior de infarto, insuficiência cardíaca e AVC.\"\n— Dra. Rhonda Patrick (FoundMyFitness)",
    tags: "Biomarcadores / Cardiovascular, sono",
    author: "Dra. Rhonda Patrick",
    source: "https://x.com/foundmyfitness/status/1870515828455522634",
  },
  {
    text: "\"Potencialize o sono profundo e o hormônio do crescimento com exposição deliberada ao calor. Saunas e banhos quentes podem aumentar o sono profundo de ondas lentas, e a sauna eleva o GH em até 16 vezes.\"\n— Dra. Rhonda Patrick (FoundMyFitness)",
    tags: "Massa magra / GH / Sono profundo, sono",
    author: "Dra. Rhonda Patrick",
    source: "https://x.com/foundmyfitness/status/1744477491031658550",
  },
  {
    text: "\"A maioria das pessoas percebe que comer perto da hora de dormir sabota a qualidade do sono. Evitar lanches noturnos e jantar cedo parece resolver a questão. Uma causa comum de insônia é temperatura corporal elevada — e picos de glicose (com aumento subsequente de insulina) contribuem para isso.\"\n— Dra. Rhonda Patrick (FoundMyFitness)",
    tags: "Higiene do sono / Insulina, sono",
    author: "Dra. Rhonda Patrick",
    source: "https://x.com/foundmyfitness/status/1946300388833133018",
  },
  {
    text: "\"Cinco horas de sono diminuíram os níveis de testosterona em 10% a 15%. A privação de sono reduz a testosterona de um homem jovem na mesma proporção que envelhecer 10 a 15 anos.\"\n— Dra. Eve Van Cauter (Universidade de Chicago; JAMA, 2011)",
    tags: "Testosterona / Massa magra, sono",
    author: "Dra. Eve Van Cauter",
    source: "https://www.sciencedaily.com/releases/2011/05/110531162142.htm",
  },
  {
    text: "\"O sono é a droga mais poderosa que existe. Para desempenho, saúde mental e bem-estar.\"\n— Bryan Johnson (fundador do projeto Blueprint / \"Don't Die\")",
    tags: "Importância geral / Saúde mental, sono",
    author: "Bryan Johnson",
    source: "https://x.com/bryan_johnson/status/1878526894980894826",
  },
  {
    text: "\"O sono é a droga mais poderosa do mundo.\"\n— Bryan Johnson (Blueprint)",
    tags: "Importância geral, sono",
    author: "Bryan Johnson",
    source: "https://x.com/bryan_johnson/status/2054294779194982637",
  },
  {
    text: "\"A frequência cardíaca de repouso antes de dormir é o marcador de saúde mais importante que você pode otimizar. Reduzi-la fará mais pela sua saúde do que qualquer outra coisa.\"\n— Bryan Johnson (Blueprint)",
    tags: "Biomarcadores / HRV, sono",
    author: "Bryan Johnson",
    source: "https://x.com/bryan_johnson/status/1895900844811567457",
  },
  {
    text: "\"Mais de um terço dos adultos americanos não está dormindo o suficiente regularmente. Dormir menos de sete horas por dia está associado a maior risco de obesidade, diabetes, hipertensão, doença cardíaca, AVC e sofrimento mental frequente.\"\n— CDC (Centers for Disease Control and Prevention, 2016)",
    tags: "Saúde pública / Biomarcadores, sono",
    author: "CDC",
    source: "https://archive.cdc.gov/www_cdc_gov/media/releases/2016/p0215-enough-sleep.html",
  },
  {
    text: "\"Uma pessoa que dorme em média menos de seis horas por noite tem 13% mais risco de mortalidade do que alguém que dorme entre sete e nove horas; entre seis e sete horas o risco é 7% maior.\"\n— RAND Corporation / RAND Europe (Hafner et al., 2016)",
    tags: "Longevidade / Mortalidade, sono",
    author: "RAND Corporation / RAND Europe",
    source: "https://www.rand.org/news/press/2016/11/30.html",
  },
  {
    text: "\"Uma boa noite de sono depende, em parte, de um bom dia em vigília: que inclua exercício, tempo ao ar livre, alimentação sensata (sem lanches noturnos), pouco ou nenhum álcool, manejo do estresse, e saber onde colocar limites no trabalho e em outros estressores.\"\n— Dr. Peter Attia (\"Outlive\", 2023, Cap. 16)",
    tags: "Higiene do sono, sono",
    author: "Dr. Peter Attia",
    source: "https://theroadtakento.com/quotes-from-outlive-by-peter-attia/",
  },
  {
    text: "\"Uma análise abrangente de duração de sono e sinais de envelhecimento em meio milhão de adultos identificou um ponto ideal — cerca de seis a oito horas de sono por dia — associado a menor risco de morte precoce e doenças.\"\n— Heidi Ledford (Nature News, 2026, comentando o estudo do MULTI Consortium publicado na Nature)",
    tags: "Longevidade / Mortalidade / Biomarcadores, sono",
    author: "Heidi Ledford",
    source: "https://www.nature.com/articles/d41586-026-01506-8",
  },
  {
    text: "\"Dormir mais ou menos do que isso (6 a 8 horas) foi associado a envelhecimento acelerado, medido por quase duas dúzias de 'relógios biológicos' que avaliam o impacto do envelhecimento no corpo.\"\n— Heidi Ledford (Nature News, 2026, sobre o estudo do MULTI Consortium em meio milhão de adultos do UK Biobank)",
    tags: "Longevidade / Envelhecimento biológico, sono",
    author: "Heidi Ledford",
    source: "https://www.nature.com/articles/d41586-026-01506-8",
  },
  {
    text: "\"O sono afeta cada órgão do corpo. E o sono é, em alguma medida, modificável. É uma ferramenta que pode ajudar.\"\n— Dra. Abigail Dove (neuroepidemiologista, Karolinska Institute, comentando o estudo do MULTI Consortium / Nature, 2026)",
    tags: "Importância geral / Biomarcadores, sono",
    author: "Dra. Abigail Dove",
    source: "https://www.nature.com/articles/d41586-026-01506-8",
  },
  {
    text: "\"O sono talvez seja mais ambiental [do que genético]. É uma mensagem forte para o público: isso pode ser modificável.\"\n— Dr. Junhao Wen (neurocientista computacional, Columbia University; autor principal do estudo MULTI Consortium / Nature, 2026)",
    tags: "Hábito / Modificabilidade, sono",
    author: "Dr. Junhao Wen",
    source: "https://www.nature.com/articles/d41586-026-01506-8",
  },
  {
    text: "\"Diferentes órgãos podem envelhecer em ritmos diferentes — e o sono ideal também varia: pelo relógio de proteínas do coração, seis horas foi associado aos melhores resultados; já pelo relógio proteico do cérebro, foram oito horas.\"\n— Dr. Junhao Wen et al. (MULTI Consortium, Nature, 2026)",
    tags: "Biomarcadores / Variação entre órgãos, sono",
    author: "Dr. Junhao Wen",
    source: "https://www.nature.com/articles/d41586-026-01506-8",
  },
  {
    text: "\"No geral, os desfechos de envelhecimento e saúde foram melhores, e as taxas de diabetes tipo 2 e depressão menores, em pessoas que dormiam entre cerca de seis e oito horas por dia, em comparação com quem dormia mais ou menos.\"\n— MULTI Consortium et al. (Nature, 2026)",
    tags: "Diabetes tipo 2 / Saúde mental / Biomarcadores, sono",
    author: "MULTI Consortium",
    source: "https://www.nature.com/articles/d41586-026-01506-8",
  },
  {
    text: "\"Os dados mostram como o sono afeta não apenas o cérebro, mas também órgãos e processos em todo o corpo. Como minha avó dizia: 'Você precisa cuidar da sua saúde como um todo'. Esses sistemas conversam entre si.\"\n— Dra. Alexandra Badea (engenheira biomédica, Duke University, comentando o estudo do MULTI Consortium / Nature, 2026)",
    tags: "Importância geral / Biomarcadores, sono",
    author: "Dra. Alexandra Badea",
    source: "https://www.nature.com/articles/d41586-026-01506-8",
  },
  {
    text: "“Nenhum nootrópico permite contornar a necessidade de sono e descanso profundo.”\n— Andrew Huberman",
    tags: "Performance / recuperação, sono",
    author: "Dr. Andrew Huberman",
    source: "https://www.hubermanlab.com/episode/using-science-to-optimize-sleep-learning-and-metabolism",
  },
  {
    text: "“Meu sono está regulando meu nível de insulina, minha sensibilidade à insulina.”\n— Dr. Rhonda Patrick",
    tags: "Sensibilidade à insulina, sono",
    author: "Dra. Rhonda Patrick",
    source: "https://www.foundmyfitness.com/episodes/the-relationship-between-sleep-and-insulin-sensitivity-david-sinclair",
  },
  {
    text: "“A variável mais preditiva da minha glicemia em qualquer dia é: como eu dormi?”\n— Dr. Ben Bikman",
    tags: "Glicemia / metabolismo, sono",
    author: "Dr. Ben Bikman",
    source: "https://www.foundmyfitness.com/episodes/ben-bikman",
  },
  {
    text: "“Sono subótimo aumenta o risco de pressão alta, açúcar no sangue e colesterol.”\n— Marie-Pierre St-Onge",
    tags: "Bioindicadores cardiometabólicos, sono",
    author: "Marie-Pierre St-Onge",
    source: "https://www.heart.org/en/news/2025/04/14/when-it-comes-to-sleep-quality-may-be-just-as-important-as-quantity",
  },
  {
    text: "“Uma das coisas mais importantes é ter um horário de sono fixo e consistente.”\n— Nour Makarem",
    tags: "Regularidade do sono, sono",
    author: "Nour Makarem",
    source: "https://www.heart.org/en/news/2021/11/19/getting-better-overall-sleep-might-be-the-key-to-better-health",
  },
  {
    text: "“Quando jovens não dormem o suficiente, nós os expomos a consequências de saúde de longo prazo.”\n— Julio Fernandez-Mendoza",
    tags: "Sono infantil / risco futuro, sono",
    author: "Julio Fernandez-Mendoza",
    source: "https://www.heart.org/en/news/2024/03/14/how-to-help-your-child-get-enough-healthy-brain-boosting-sleep",
  },
  {
    text: "“Isso demonstra a importância do sono profundo não apenas para o cérebro, mas para o resto do corpo.”\n— Eve Van Cauter",
    tags: "Sono profundo / insulina, sono",
    author: "Dra. Eve Van Cauter",
    source: "https://www.reuters.com/article/world/lack-of-deep-sleep-may-raise-diabetes-risk-idUSN31588267/",
  },
  {
    text: "“Sono é medicina preventiva.”\n— Katherine Dudley",
    tags: "Prevenção / bem-estar, sono",
    author: "Katherine Dudley",
    source: "https://www.health.harvard.edu/blog/weekend-catch-up-sleep-wont-fix-the-effects-of-sleep-deprivation-on-your-waistline-2019092417861",
  },
  {
    text: "“Ter uma boa noite de sono todas as noites é vital para a saúde cardiovascular.”\n— American Heart Association",
    tags: "Saúde cardiovascular, sono",
    author: "American Heart Association",
    source: "https://www.heart.org/en/healthy-living/healthy-lifestyle/sleep",
  },
  {
    text: "“Dormir pouco pode ter impacto direto nas funções cardiovascular, endócrina e imune.”\n— Aric Prather",
    tags: "Bioindicadores sistêmicos, sono",
    author: "Aric Prather",
    source: "https://www.reuters.com/article/business/healthcare-pharmaceuticals/short-sleep-may-be-tied-to-cold-or-infection-risk-idUSKCN0X81V6/",
  },
  {
    text: "“Durma o necessário todas as noites e evite estresse crônico.”\n— Stoyan Dimitrov",
    tags: "Imunidade / recuperação, sono",
    author: "Stoyan Dimitrov",
    source: "https://www.reuters.com/article/business/healthcare-pharmaceuticals/researchers-discover-how-sleep-helps-the-body-fight-germs-idUSKCN1Q12SB/",
  },
  {
    text: "“A privação de sono dispara uma solidão viral.”\n— Dr. Matthew Walker",
    tags: "Saúde mental / solidão, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/sleep-deprivation-linked-to-loneliness",
  },
  {
    text: "“A amígdala ficou 60% mais reativa em condições de falta de sono.”\n— Dr. Matthew Walker",
    tags: "Ansiedade / reatividade emocional, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/sleep-deprivation-may-be-correlated-with-increased-impulsivity-and-psychiatric-disorders-matthew-walker",
  },
  {
    text: "“Não é o tempo que cura todas as feridas, mas o tempo durante o sono REM.”\n— Dr. Matthew Walker",
    tags: "Sono REM / regulação emocional, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/rem-sleep-deep-sleep-cardiovascular-and-emotional-health",
  },
  {
    text: "“Pessoas muito ansiosas são as mais vulneráveis ao impacto da falta de sono.”\n— Dr. Matthew Walker",
    tags: "Ansiedade / insônia, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/anxiety-cortisol-meditation-effects-on-insomnia",
  },
  {
    text: "“Enquanto você dorme, seu cérebro está trabalhando.”\n— Maiken Nedergaard",
    tags: "Cérebro / limpeza neural, sono",
    author: "Maiken Nedergaard",
    source: "https://newsinhealth.nih.gov/2021/04/good-sleep-good-health",
  },
  {
    text: "“O sono ajuda seu cérebro a aprender, lembrar e criar.”\n— NIH News in Health",
    tags: "Aprendizado / memória, sono",
    author: "NIH News in Health",
    source: "https://newsinhealth.nih.gov/2021/04/good-sleep-good-health",
  },
  {
    text: "“O sono ajuda você a pensar com mais clareza, ter reflexos mais rápidos e focar melhor.”\n— NIH News in Health",
    tags: "Cognição / foco, sono",
    author: "NIH News in Health",
    source: "https://newsinhealth.nih.gov/2013/04/benefits-slumber",
  },
  {
    text: "“Dormir antes de aprender ajuda a preparar o cérebro para formar memórias.”\n— Dr. Matthew Walker",
    tags: "Memória / aprendizado, sono",
    author: "Dr. Matthew Walker",
    source: "https://newsinhealth.nih.gov/2013/04/sleep-it",
  },
  {
    text: "“Sono ruim tem impacto adverso no pensamento.”\n— Lawrence Epstein",
    tags: "Clareza mental, sono",
    author: "Lawrence Epstein",
    source: "https://www.health.harvard.edu/mind-and-mood/sharpen-thinking-skills-with-a-better-nights-sleep",
  },
  {
    text: "“A privação de sono faz partes do cérebro responsáveis por funções superiores trabalharem pior.”\n— Kerry Ressler",
    tags: "Funções executivas, sono",
    author: "Kerry Ressler",
    source: "https://www.health.harvard.edu/mind-and-mood/protect-your-brain-from-stress",
  },
  {
    text: "“Quem dormia menos de cinco horas por noite tinha o dobro de chance de desenvolver demência.”\n— Harvard Health",
    tags: "Demência / Alzheimer, sono",
    author: "Harvard Health",
    source: "https://www.health.harvard.edu/blog/sleep-well-and-reduce-your-risk-of-dementia-and-death-2021050322508",
  },
  {
    text: "“Dormir seis horas ou menos aos 50, 60 e 70 anos foi associado a aumento de 30% no risco de demência.”\n— Harvard Health",
    tags: "Demência / meia-idade, sono",
    author: "Harvard Health",
    source: "https://www.health.harvard.edu/blog/sleep-well-and-reduce-your-risk-of-dementia-and-death-2021050322508",
  },
  {
    text: "“Quando dormimos, as células cerebrais encolhem, abrindo espaço para eliminar beta-amiloide.”\n— Harvard Health",
    tags: "Alzheimer / beta-amiloide, sono",
    author: "Harvard Health",
    source: "https://www.health.harvard.edu/blog/sleep-well-and-reduce-your-risk-of-dementia-and-death-2021050322508",
  },
  {
    text: "“Se você não dorme o suficiente, o cérebro não tem tempo para drenar beta-amiloide.”\n— Harvard Health",
    tags: "Alzheimer / sistema glinfático, sono",
    author: "Harvard Health",
    source: "https://www.health.harvard.edu/blog/sleep-well-and-reduce-your-risk-of-dementia-and-death-2021050322508",
  },
  {
    text: "“Cada redução percentual no tempo em sono REM foi associada a aumento de 9% no risco de demência.”\n— Reuters Health",
    tags: "REM / demência, sono",
    author: "Reuters Health",
    source: "https://www.reuters.com/article/business/healthcare-pharmaceuticals/lack-of-rem-sleep-tied-to-increased-risk-of-dementia-idUSKCN1BA2C2/",
  },
  {
    text: "“O sono é vitalmente importante para a saúde geral e deve ser prioridade.”\n— Matthew Pase",
    tags: "Cognição / demência, sono",
    author: "Matthew Pase",
    source: "https://www.reuters.com/article/business/healthcare-pharmaceuticals/sleep-problems-in-older-adults-linked-to-cognitive-decline-and-dementia-idUSKBN1ZE2GL/",
  },
  {
    text: "“Ronco pesado e apneia do sono são assassinos.”\n— Dr. Matthew Walker",
    tags: "Apneia / Alzheimer, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/apoe4-sleep-apnea-impaired-deep-sleep",
  },
  {
    text: "“O sono não é um luxo descartável; é uma necessidade biológica inegociável.”\n— Dr. Matthew Walker",
    tags: "Necessidade biológica, sono",
    author: "Dr. Matthew Walker",
    source: "https://richroll.com/podcast/matthew-walker-600/",
  },
  {
    text: "“Eu construí minha existência inteira em torno do sono.”\n— Bryan Johnson",
    tags: "Disciplina / rotina, sono",
    author: "Bryan Johnson",
    source: "https://blueprint.bryanjohnson.com/blogs/news/wired-profile-bryan-johnson",
  },
  {
    text: "“Sono de alta qualidade mudou minha vida.”\n— Bryan Johnson",
    tags: "Longevidade / hábito, sono",
    author: "Bryan Johnson",
    source: "https://blueprint.bryanjohnson.com/blogs/news/how-i-fixed-my-terrible-sleep",
  },
  {
    text: "“O sono evoluiu por razões metabólicas, muito antes de existirem cérebros.”\n— Veronique Greenwood",
    tags: "Importância evolutiva, sono",
    author: "Veronique Greenwood",
    source: "https://www.quantamagazine.org/sleep-evolved-before-brains-hydras-are-living-proof-20210518/",
  },
  {
    text: "“Dormir pode parecer perda de tempo, mas é crítico para uma vida desperta saudável.”\n— Alice Gregory",
    tags: "Importância evolutiva, sono",
    author: "Alice Gregory",
    source: "https://www.sciencefocus.com/the-human-body/why-did-sleep-evolve",
  },
  {
    text: "“Se o sono não serve a uma função absolutamente vital, é o maior erro que a evolução já cometeu.”\n— Dr. Matthew Walker",
    tags: "Argumento evolutivo, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.jordanharbinger.com/matthew-walker-unlocking-the-power-of-sleep-and-dreams/",
  },
  {
    text: "“Você não escolhe se é matutino ou vespertino; isso é geneticamente determinado.”\n— Dr. Matthew Walker",
    tags: "Cronotipo, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/chronotypes-early-riser-or-night-owl",
  },
  {
    text: "“Acordar cedo demais pode fazer você perder quase 80% do seu sono REM.”\n— Dr. Matthew Walker",
    tags: "REM / acordar cedo, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/chronotypes-early-riser-or-night-owl",
  },
  {
    text: "“O primeiro ciclo de sono é quando ocorre uma grande liberação de hormônio do crescimento.”\n— Dr. Gina Poe",
    tags: "Hormônio do crescimento / massa magra, sono",
    author: "Dr. Gina Poe",
    source: "https://www.hubermanlab.com/episode/dr-gina-poe-use-sleep-to-enhance-learning-memory-and-emotional-state",
  },
  {
    text: "“Dormir no mesmo horário ajuda a garantir a liberação adequada de hormônio do crescimento nas primeiras horas do sono.”\n— Andrew Huberman / Gina Poe",
    tags: "GH / regularidade, sono",
    author: "Dr. Andrew Huberman / Gina Poe",
    source: "https://www.hubermanlab.com/episode/dr-gina-poe-use-sleep-to-enhance-learning-memory-and-emotional-state",
  },
  {
    text: "“Uma noite de privação de sono reduziu a síntese de proteína muscular em 18%.”\n— FoundMyFitness",
    tags: "Massa magra / síntese proteica, sono",
    author: "FoundMyFitness",
    source: "https://www.foundmyfitness.com/tags/sleep",
  },
  {
    text: "“Você realmente precisa de algum grau de escuridão à noite.”\n— Dr. Matthew Walker",
    tags: "Luz azul / melatonina, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/blue-light-detrimental-to-healthy-sleep",
  },
  {
    text: "“O corpo precisa de um sinal térmico para dizer: é hora de dormir.”\n— Dr. Matthew Walker",
    tags: "Temperatura / indução do sono, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/temperature-triggers-sleep",
  },
  {
    text: "“Se você encurta qualquer pilar do sono, cria déficit no cérebro e no corpo.”\n— Dr. Matthew Walker",
    tags: "Profundidade / duração / regularidade, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/four-pillars-of-sleep-depth-duration-continuity-and-regularity",
  },
  {
    text: "“Boa higiene do sono significa também cultivar um bom ambiente para dormir.”\n— Dayna Johnson",
    tags: "Higiene do sono, sono",
    author: "Dayna Johnson",
    source: "https://www.heart.org/en/news/2023/03/16/what-happens-when-we-sleep-and-why-we-need-just-the-right-amount-each-night",
  },
  {
    text: "“A privação de sono aumenta a preferência por carboidratos e lanches açucarados.”\n— Dr. Matthew Walker",
    tags: "Apetite / açúcar, sono",
    author: "Dr. Matthew Walker",
    source: "https://www.foundmyfitness.com/episodes/sleep-deprivation-preference-for-carbohydrates-and-sugary-snacks",
  },
  {
    text: "“Dormir melhor pode facilitar seguir um plano de perda de peso.”\n— American Heart Association",
    tags: "Composição corporal / adesão, sono",
    author: "American Heart Association",
    source: "https://www.heart.org/en/news/2023/03/03/getting-better-sleep-may-make-it-easier-to-stick-to-a-weight-loss-plan",
  },
  {
    text: "“O sono deveria ser incluído como medida de saúde cardíaca, assim como dieta e exercício.”\n— American Heart Association",
    tags: "Saúde cardiovascular, sono",
    author: "American Heart Association",
    source: "https://www.heart.org/en/news/2020/03/06/sleep-should-be-added-as-measure-of-heart-health-study-says",
  },
  {
    text: "“Padrões irregulares de sono podem impactar negativamente a saúde do coração.”\n— American Heart Association",
    tags: "Regularidade / coração, sono",
    author: "American Heart Association",
    source: "https://www.heart.org/en/news/2019/03/08/irregular-sleep-could-negatively-impact-heart-health",
  },
];
